repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitspace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: check-yaml
        name: check-yaml
      - id: check-toml
        name: check-toml
      - id: check-added-large-files
        name: check-added-large-files
  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.272
    hooks:
      - id: ruff
  - repo: https://github.com/fredrikaverpil/creosote
    rev: v2.6.1
    hooks:
      - id: creosote
        args:
          - --venv=__pypackages__/3.11/lib
          - --paths=starlette_async_jinja
  #          - --deps-file=pyproject.toml
  #          - --sections=project.dependencies
  - repo: https://github.com/ikamensh/flynt/
    rev: '0.78'
    hooks:
      - id: flynt
  - repo: https://github.com/dosisod/refurb
    rev: v1.16.0
    hooks:
      - id: refurb
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.313
    hooks:
      - id: pyright
  #  - repo: https://github.com/pdoc3/pdoc
  #    rev: master
  #    hooks:
  #      - id: pdoc
  #        name: pdoc
  #        entry: pdoc --html -f -o docs module1 module2 module3
  #        language_version: python3.11
  #        require_serial: true
  #        types: [ python ]
  #        always_run: true
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.272
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black
        language_version: python3.11
