repos:
  - repo: https://github.com/pdm-project/pdm
    rev: 2.13.3  # a PDM release exposing the hook
    hooks:
      - id: pdm-lock-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitspace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: check-yaml
        name: check-yaml
      - id: check-toml
        name: check-toml
      - id: check-added-large-files
        name: check-added-large-files
  - repo: https://github.com/psf/black
    rev: '24.3.0'
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
  - repo: https://github.com/fredrikaverpil/creosote
    rev: v3.0.0
    hooks:
      - id: creosote
  - repo: https://github.com/ikamensh/flynt/
    rev: '1.0.1'
    hooks:
      - id: flynt
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
        args: [--ignore-words-list, "crate,uptodate"]
  - repo: local
    hooks:
      - id: autotyping
        name: autotyping
        entry: python -m libcst.tool codemod autotyping.AutotypeCommand
        args:
          - --aggressive
          - --only-without-imports
          - --show-successes
          - --include-generated
          - --guess-common-names
          - starlette_async_jinja
        types_or: [ python, pyi ]
        language: python
        files: \.py$
        additional_dependencies:
          - autotyping>=23.3.0
          - libcst>=0.4.9
  - repo: https://github.com/dosisod/refurb
    rev: v2.0.0
    hooks:
      - id: refurb
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.358
    hooks:
      - id: pyright
  #  - repo: https://github.com/pdoc3/pdoc
  #    rev: master
  #    hooks:
  #      - id: pdoc
  #        name: pdoc
  #        entry: pdoc --html -f -o docs module1 module2 module3
  #        language_version: python3.11
  #        require_serial: true
  #        types: [ python ]
  #        always_run: true
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: '24.3.0'
    hooks:
      - id: black
