repos:
  - repo: local
    hooks:
      - id: validate-regex-patterns
        name: validate-regex-patterns
        entry: uv run python -m crackerjack.tools.validate_regex_patterns
        language: system
        files: \.py$
        exclude: ^\.venv/|^src/
      - id: skylos
        name: skylos-dead-code-detection
        entry: skylos
        language: system
        args: ["starlette_async_jinja", "--exclude", "tests"]
        pass_filenames: false
        exclude: ^tests/|^src/
        stages: ["pre-push", "manual"]
      - id: zuban
        name: zuban-type-checking
        entry: uv run zuban check
        language: system
        args: ["--config-file", "mypy.ini", "./starlette_async_jinja"]
        pass_filenames: false
        exclude: ^tests/|^src/
        stages: ["pre-push", "manual"]
      - id: pyright
        name: pyright-type-checking
        entry: uv run pyright
        language: system
        files: ^starlette_async_jinja/.*\.py$
        exclude: ^crackerjack/(mcp|plugins)/.*\.py$|crackerjack/code_cleaner\.py$|^src/
        stages: ["pre-push", "manual"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        exclude: ^\.venv/|^src/
      - id: end-of-file-fixer
        name: end-of-file-fixer
        exclude: ^\.venv/|^src/
      - id: check-yaml
        name: check-yaml
        exclude: ^\.venv/|^src/
      - id: check-toml
        name: check-toml
        exclude: ^\.venv/|^src/
      - id: check-added-large-files
        name: check-added-large-files
        exclude: ^\.venv/|^src/
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.15
    hooks:
      - id: uv-lock
        files: ^ pyproject\.toml$
        exclude: ^src/
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        exclude: uv\.lock|pyproject\.toml|tests/.*|docs/.*|.*\.md|^src/
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "-ll"]
        files: ^starlette_async_jinja/.*\.py$
        exclude: ^tests/|^src/
        stages: ["pre-push", "manual"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: ^\.venv/|^src/
        additional_dependencies: ["tomli"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        exclude: ^\.venv/|^src/
      - id: ruff-format
        exclude: ^\.venv/|^src/
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        exclude: ^\.venv/|^src/
        additional_dependencies: ["mdformat-ruff"]
  - repo: https://github.com/fredrikaverpil/creosote
    rev: v4.1.0
    hooks:
      - id: creosote
        exclude: ^\.venv/|^src/
        stages: ["pre-push", "manual"]
  - repo: https://github.com/rohaquinlop/complexipy-pre-commit
    rev: v3.3.0
    hooks:
      - id: complexipy
        args: ["-d", "low", "--max-complexity-allowed", "15"]
        files: ^starlette_async_jinja/.*\.py$
        exclude: ^(\.venv/|tests/)|^src/
        stages: ["pre-push", "manual"]
  - repo: https://github.com/dosisod/refurb
    rev: v2.1.0
    hooks:
      - id: refurb
        files: ^starlette_async_jinja/.*\.py$
        exclude: ^tests/|^src/
        stages: ["pre-push", "manual"]
