repos:
  # File structure and format validators - check structure first
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
        verbose: true
      - id: end-of-file-fixer
        name: end-of-file-fixer
        verbose: true
      - id: check-yaml
        name: check-yaml
        verbose: true
      - id: check-toml
        name: check-toml
        verbose: true
      - id: check-added-large-files
        name: check-added-large-files
        verbose: true

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        verbose: true

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
      - id: pyproject-fmt
        args: ["-n"]
        verbose: true

  # Package management - once structure is valid
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.15
    hooks:
      - id: uv-lock
        files: ^pyproject\.toml$
        verbose: true

  # Security check - early to prevent credential leaks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: 'uv\.lock|pyproject\.toml|tests/.*|docs/.*|.*\.md'
        verbose: true

  # Code quality tier 1 - quick fixes
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        verbose: true
        additional_dependencies:
          - tomli

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff-check
        verbose: true
        args: [--output-format=json]
      - id: ruff-format
        verbose: true

  # Code quality tier 2 - analysis
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.14'
    hooks:
      - id: vulture
        verbose: true

  - repo: https://github.com/fredrikaverpil/creosote
    rev: v4.0.3
    hooks:
      - id: creosote
        verbose: true

  - repo: https://github.com/rohaquinlop/complexipy-pre-commit
    rev: v3.0.0
    hooks:
      - id: complexipy
        args: ["-d", "low", "-j"]
        verbose: true

  - repo: https://github.com/dosisod/refurb
    rev: v2.1.0
    hooks:
      - id: refurb
        verbose: true

  # Code quality tier 3 - thorough checks
  - repo: local
    hooks:
      - id: autotyping
        name: autotyping
        entry: python -m autotyping
        args:
          - --aggressive
          - --only-without-imports
          - --guess-common-names
          - starlette_async_jinja
        types_or: [ python, pyi ]
        language: python
        files: \.py$
        verbose: true
        additional_dependencies:
          - autotyping>=24.3.0
          - libcst>=1.1.0

  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.5'
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "--format", "json"]
        verbose: true

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright
        verbose: true
        args: ["--outputjson"]
