repos:
  # File structure and format validators - check structure first
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace
      - id: end-of-file-fixer
        name: end-of-file-fixer
      - id: check-yaml
        name: check-yaml
      - id: check-toml
        name: check-toml
      - id: check-added-large-files
        name: check-added-large-files

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
      - id: pyproject-fmt

  # Package management - once structure is valid
  - repo: https://github.com/pdm-project/pdm
    rev: 2.24.2
    hooks:
      - id: pdm-lock-check
      - id: pdm-sync
        additional_dependencies:
          - keyring

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.12
    hooks:
      - id: uv-lock
        files: ^pyproject\.toml$

  # Security check - early to prevent credential leaks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: 'pdm\.lock|uv\.lock|pyproject\.toml|tests/.*|docs/.*|.*\.md'

  # Code quality tier 1 - quick fixes
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff-check
      - id: ruff-format

  # Code quality tier 2 - analysis
  - repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.14'
    hooks:
      - id: vulture

  - repo: https://github.com/fredrikaverpil/creosote
    rev: v4.0.3
    hooks:
      - id: creosote

  - repo: https://github.com/dosisod/refurb
    rev: v2.1.0
    hooks:
      - id: refurb

  # Code quality tier 3 - thorough checks
  - repo: local
    hooks:
      - id: autotyping
        name: autotyping
        entry: python -m autotyping
        args:
          - --aggressive
          - --only-without-imports
          - --guess-common-names
          - starlette_async_jinja
        types_or: [ python, pyi ]
        language: python
        files: \.py$
        additional_dependencies:
          - autotyping>=24.3.0
          - libcst>=1.1.0

  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.3'
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright

  #  - repo: https://github.com/pdoc3/pdoc
  #    rev: master
  #    hooks:
  #      - id: pdoc
  #        name: pdoc
  #        entry: pdoc --html -f -o docs module1 module2 module3
  #        language_version: python3.11
  #        require_serial: true
  #        types: [ python ]
  #        always_run: true
